server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/umbrella?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dkdldb12
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true
        format_sql: true